# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - twit-follow-stats-staging

on:
  push:
    branches:
      - staging

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: staging

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: npm setup, build
      run: |
        npm install
        npm run setup-deps
        npm run build

    - name: Create .env file
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_NODE_ENV: development
        envkey_TWITTER_BEARER: ${{ secrets.TWITTER_BEARER }}
        envkey_CORS_ORIGIN: https://twit-follow-stats-staging.azurewebsites.net
        directory: api

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'twit-follow-stats-staging'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_904019c9f0e24556916b9d903e49ff36 }}
        package: .
